name: C/C++ CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: install gtest
              run: sudo apt-get install -y libgtest-dev libgmock-dev 

            - name: checkout
              uses: actions/checkout@v4
            
            - name: configure
              run: mkdir build; cd build; cmake ..;

            - name: build tests
              run: cd build; make;

            - name: run tests
              run: cd build; ./test1;

