name: C/C++ CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
            - uses: actions/checkout@v4
            
            - name: configure
              run: mkdir build; cd build; cmake ..;

            - name: build
              run: cd build; make;

            - name: execute
              run: cd build; ./demo;

